spring.application.name=api-gateway

server.port=8082

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Discovery Locator (rotas dinâmicas via Eureka)
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Converte o ID dos serviços registrados no Eureka para minúsculas ao criar rotas dinâmicas
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# SWAGGER dinamico
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha