spring.application.name=eureka-server

# Porta padrão do Eureka Server (dashboard e endpoint /eureka)
server.port=8761

# Como é SERVER, não registra a si mesmo no Eureka
eureka.client.register-with-eureka=false

# Como é SERVER, não precisa buscar/cachar o registry
eureka.client.fetch-registry=false

# defaultZone precisa ser exatamente assim (camelCase), pois serviceUrl é um Map
eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/